version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: logistream-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    env_file:
      - ../.env
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    container_name: logistream-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    env_file:
      - ../.env
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka-native
    container_name: logistream-kafka
    restart: unless-stopped
    ports:
      - '9092:9092'
    env_file:
      - ../.env
    volumes:
      - kafka-data:/apache/kafka-native
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1',
        ]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  mongo-data:
  redis-data:
  kafka-data:
